// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6HUpRj4lc-JE40AJL70Vwc5fDOA6Xu44',
    appId: '1:570657413949:web:d4592ef7c99da6b24e0354',
    messagingSenderId: '570657413949',
    projectId: 'studygether-final',
    authDomain: 'studygether-final.firebaseapp.com',
    storageBucket: 'studygether-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAceSmJg-M-i4E9DHV3ZQZO7eMMWn5SQkE',
    appId: '1:570657413949:android:8775b29e9ba704c04e0354',
    messagingSenderId: '570657413949',
    projectId: 'studygether-final',
    storageBucket: 'studygether-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLoG2xFjBahUP8etJUn7So-jAALb8lxbo',
    appId: '1:570657413949:ios:875a23c74256f9854e0354',
    messagingSenderId: '570657413949',
    projectId: 'studygether-final',
    storageBucket: 'studygether-final.appspot.com',
    iosBundleId: 'com.example.studygether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLoG2xFjBahUP8etJUn7So-jAALb8lxbo',
    appId: '1:570657413949:ios:7843eeeac25fff254e0354',
    messagingSenderId: '570657413949',
    projectId: 'studygether-final',
    storageBucket: 'studygether-final.appspot.com',
    iosBundleId: 'com.example.studygether.RunnerTests',
  );
}
